version: '3'
services:
  pgdb:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRESS_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata